[MERPWH-1107][v13][ADD] added group 'Validate Inventory by Inventory User'
ventor-tech/merp pull request #254
Opened 2022-05-31 16:43 UTC by KirillVorobey

2022-05-31 21:38 UTC, okuryan requested changes

2022-05-31 21:38 UTC, okuryan commented on ventor_base/security/groups.xml
> +        <field name="name">Validate Inventory by Inventory User</field>
Не надо так уже называть роль

Достаточно "Validate Inventory"

2022-05-31 21:38 UTC, okuryan commented on ventor_base/security/groups.xml
> +    </record>
Нужно чтобы эту новую роль также наследовал Inventory - Administrator

Чтобы поведение администратора не изменилось (он как мог валидировать инвентори, так и остался мочь ее валидировать)

2022-05-31 21:38 UTC, okuryan commented on ventor_base/models/stock_inventory.py
> +        return res
Что-то я нифига не понял завем вообще был переопределен этот метод

2022-05-31 21:38 UTC, okuryan commented on ventor_base/__manifest__.py
> +    'version': '13.0.1.3.10',
Сделай версию 1.4.0

Только уточни у мобильной команды что это не сломает ничего )))

Дело в том что последняя цифра означает багфикс релиз/минорный фичи. А ты же не баги фиксишь 

Вторая цифра релиз в котором добавляются серьезные фичи. Мне кажется новая группа вполне себе претендует на фичу

2022-06-01 06:50 UTC, KirillVorobey commented on ventor_base/models/stock_inventory.py
> +        return res
Переопределил этот метод, чтобы если у нас группа Validate Inventory=True, то передаем контекст и нет разницы User валидирует ивентаризацию или Администратор.

2022-06-08 17:11 UTC, merged