[MERPWH-1093][v13_rel][v13] creating ventor settings
ventor-tech/merp pull request #261
Opened 2022-06-10 13:08 UTC by KirillVorobey

2022-06-12 21:24 UTC, okuryan requested changes

2022-06-12 21:24 UTC, okuryan commented on ventor_base/models/ventor_option_setting.py
> +    is_set = fields.Boolean()
А бывают в венторе опции кроме как True/False?
Может бывает еще какой дропдаун там (ссылка на обьект и так далее) - типа склад по умолчанию 

Уточняю на всякий случай так как сейчас в реализации возможны только чекбоксики
Я бы сделал скрытое поле value. И значение читал из него. И если юзер поставил чекбокс is_set то в это Char поле запишется True. Иначе False
Это более гибко. Это аналогично как сделано в Оду System Parameters. 

Только мы юзабельнее сделаем

2022-06-12 21:24 UTC, okuryan commented on ventor_base/models/ventor_option_setting.py
> +                set.technical_name: set.is_set
Соответственно тут будет в значении не is_set , а value поле

2022-06-12 21:24 UTC, okuryan commented on ventor_base/views/ventor_option_setting.xml
> +            <field name="view_mode">tree,form</field>
Наверное пока не надо Form для вьюхи.
Все должно редактироваться в таблице (inline)

2022-06-13 06:53 UTC, KirillVorobey commented on ventor_base/models/ventor_option_setting.py
> +    is_set = fields.Boolean()
В венторе есть дропдауны в настройках для Operation Types. Я данную реализацию не изменял, т.к. у нас там много кастомной логики. Единственное, что вынес ее в отдельное подменю Warehouse Operations.

2022-06-13 06:53 UTC, KirillVorobey commented on ventor_base/views/ventor_option_setting.xml
> +            <field name="view_mode">tree,form</field>
Done

2022-10-10 15:03 UTC, merged